version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.2.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL_DIFFERENT_HOST://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      JMX_PORT: 9997
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
  spark-master:
    container_name: spark-master
    image: cluster-apache-spark:3.2.1
    ports:
      - 9090:8080
      - 7077:7077
    depends_on:
      - kafka
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      SPARK_LOCAL_IP: spark-master
      SPARK_WORKLOAD: master
  spark-worker-1:
    container_name: spark-worker-1
    image: cluster-apache-spark:3.2.1
    ports:
      - 9091:8080
      - 7000:7000
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_DRIVER_MEMORY: 1G
      SPARK_EXECUTOR_MEMORY: 1G
      SPARK_WORKLOAD: worker
      SPARK_LOCAL_IP: spark-worker-1
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
  spark-worker-2:
    container_name: spark-worker-2
    image: cluster-apache-spark:3.2.1
    ports:
      - 9093:8080
      - 7001:7000
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_DRIVER_MEMORY: 1G
      SPARK_EXECUTOR_MEMORY: 1G
      SPARK_WORKLOAD: worker
      SPARK_LOCAL_IP: spark-worker-2
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
